INSERT INTO noticias (titulo,texto,img,created_at,creador_id)
    VALUES ('El betis gana la Champions', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis orci at dolor mollis mollis. Suspendisse volutpat, sapien in sagittis aliquet, urna velit aliquam leo, non iaculis justo ante in tortor. Maecenas in tellus libero. Cras iaculis consectetur tellus eget pretium. Phasellus mollis orci a malesuada vestibulum. Suspendisse potenti. Morbi tincidunt tincidunt massa, ut maximus purus pellentesque eu. Nullam in consequat risus. Nullam aliquet vulputate nibh, id volutpat metus dapibus non. Donec vitae porta enim. Vestibulum urna leo, dapibus in ullamcorper quis, tempus in nibh. Curabitur semper augue eleifend ultricies ultrices.

Etiam iaculis sapien ante, eu feugiat dui venenatis id. Aliquam ac sodales enim. Proin vitae neque scelerisque, tempus urna sit amet, volutpat erat. Aenean dolor ante, auctor non purus eget, lacinia venenatis ligula. Vestibulum ullamcorper maximus nunc, sollicitudin mollis tortor vestibulum vitae. Duis feugiat quis ipsum in fringilla. Nam mollis arcu sed sagittis fringilla. Praesent gravida ipsum eu semper vehicula. Quisque sit amet auctor enim. Maecenas ut eros viverra dui placerat blandit nec eget massa. Integer mattis auctor ante, ut luctus libero faucibus quis. Aliquam pulvinar lacus et nisl dignissim volutpat. Etiam sit amet orci a turpis sollicitudin luctus.

Praesent finibus purus at massa ultricies vulputate. Etiam pellentesque, dui nec interdum interdum, leo dolor porta urna, ut eleifend erat eros non risus. Quisque venenatis venenatis ultrices. Quisque nec tortor id justo egestas fringilla sit amet et augue. Curabitur vulputate mauris mi, gravida pulvinar orci sodales in. Donec congue, odio vel elementum venenatis, sapien enim aliquet nibh, eget lacinia mi est ac tortor. Proin dolor augue, porttitor eget lobortis eget, aliquet vitae turpis.

Nulla hendrerit et diam eu facilisis. Aliquam justo ipsum, consectetur ac faucibus quis, dictum placerat tellus. Praesent ullamcorper bibendum orci, nec hendrerit dolor efficitur pellentesque. Duis at mollis est. Nullam laoreet bibendum hendrerit. Vivamus congue rhoncus mauris, eu sodales lorem congue non. Aliquam massa leo, euismod bibendum ornare vel, tincidunt eu metus. Maecenas in nisl et ipsum scelerisque aliquet. Integer consectetur sem non enim blandit fermentum.

Cras libero elit, posuere sed suscipit ut, tincidunt sed nisi. Nulla vel odio vestibulum, cursus sapien id, commodo nulla. Donec vulputate aliquam libero, vitae aliquet ipsum dignissim quis. Nullam consectetur egestas nibh, vitae pretium urna varius quis. Ut quis tincidunt erat. Nam tempus, sem at accumsan sagittis, massa massa hendrerit metus, vitae venenatis nunc ligula semper enim. Proin condimentum, mi nec ultricies porta, est odio scelerisque sem, et facilisis ipsum velit eu dolor. Donec porta enim at interdum laoreet. Cras bibendum libero arcu, sed lacinia ligula vehicula posuere. Aenean eget euismod magna, at maximus mauris. Vestibulum semper, eros eu placerat porttitor, magna odio tincidunt ligula, id tincidunt ipsum erat at diam. Nunc fermentum dui in tellus hendrerit, a ultrices ligula venenatis. Sed in risus a massa dictum feugiat. Aliquam erat volutpat. ', 'https://www.dropbox.com/s/oeqfye2gh9pmhdu/descarga.png?dl=1', '2018-03-06',1),
('El betis gana la Champions', '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis orci at dolor mollis mollis. Suspendisse volutpat, sapien in sagittis aliquet, urna velit aliquam leo, non iaculis justo ante in tortor. Maecenas in tellus libero. Cras iaculis consectetur tellus eget pretium. Phasellus mollis orci a malesuada vestibulum. Suspendisse potenti. Morbi tincidunt tincidunt massa, ut maximus purus pellentesque eu. Nullam in consequat risus. Nullam aliquet vulputate nibh, id volutpat metus dapibus non. Donec vitae porta enim. Vestibulum urna leo, dapibus in ullamcorper quis, tempus in nibh. Curabitur semper augue eleifend ultricies ultrices.

Etiam iaculis sapien ante, eu feugiat dui venenatis id. Aliquam ac sodales enim. Proin vitae neque scelerisque, tempus urna sit amet, volutpat erat. Aenean dolor ante, auctor non purus eget, lacinia venenatis ligula. Vestibulum ullamcorper maximus nunc, sollicitudin mollis tortor vestibulum vitae. Duis feugiat quis ipsum in fringilla. Nam mollis arcu sed sagittis fringilla. Praesent gravida ipsum eu semper vehicula. Quisque sit amet auctor enim. Maecenas ut eros viverra dui placerat blandit nec eget massa. Integer mattis auctor ante, ut luctus libero faucibus quis. Aliquam pulvinar lacus et nisl dignissim volutpat. Etiam sit amet orci a turpis sollicitudin luctus.

Praesent finibus purus at massa ultricies vulputate. Etiam pellentesque, dui nec interdum interdum, leo dolor porta urna, ut eleifend erat eros non risus. Quisque venenatis venenatis ultrices. Quisque nec tortor id justo egestas fringilla sit amet et augue. Curabitur vulputate mauris mi, gravida pulvinar orci sodales in. Donec congue, odio vel elementum venenatis, sapien enim aliquet nibh, eget lacinia mi est ac tortor. Proin dolor augue, porttitor eget lobortis eget, aliquet vitae turpis.

Nulla hendrerit et diam eu facilisis. Aliquam justo ipsum, consectetur ac faucibus quis, dictum placerat tellus. Praesent ullamcorper bibendum orci, nec hendrerit dolor efficitur pellentesque. Duis at mollis est. Nullam laoreet bibendum hendrerit. Vivamus congue rhoncus mauris, eu sodales lorem congue non. Aliquam massa leo, euismod bibendum ornare vel, tincidunt eu metus. Maecenas in nisl et ipsum scelerisque aliquet. Integer consectetur sem non enim blandit fermentum.

Cras libero elit, posuere sed suscipit ut, tincidunt sed nisi. Nulla vel odio vestibulum, cursus sapien id, commodo nulla. Donec vulputate aliquam libero, vitae aliquet ipsum dignissim quis. Nullam consectetur egestas nibh, vitae pretium urna varius quis. Ut quis tincidunt erat. Nam tempus, sem at accumsan sagittis, massa massa hendrerit metus, vitae venenatis nunc ligula semper enim. Proin condimentum, mi nec ultricies porta, est odio scelerisque sem, et facilisis ipsum velit eu dolor. Donec porta enim at interdum laoreet. Cras bibendum libero arcu, sed lacinia ligula vehicula posuere. Aenean eget euismod magna, at maximus mauris. Vestibulum semper, eros eu placerat porttitor, magna odio tincidunt ligula, id tincidunt ipsum erat at diam. Nunc fermentum dui in tellus hendrerit, a ultrices ligula venenatis. Sed in risus a massa dictum feugiat. Aliquam erat volutpat. ', 'https://www.dropbox.com/s/oeqfye2gh9pmhdu/descarga.png?dl=1', '2018-03-06',1),
('El betis gana la Champions', '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis orci at dolor mollis mollis. Suspendisse volutpat, sapien in sagittis aliquet, urna velit aliquam leo, non iaculis justo ante in tortor. Maecenas in tellus libero. Cras iaculis consectetur tellus eget pretium. Phasellus mollis orci a malesuada vestibulum. Suspendisse potenti. Morbi tincidunt tincidunt massa, ut maximus purus pellentesque eu. Nullam in consequat risus. Nullam aliquet vulputate nibh, id volutpat metus dapibus non. Donec vitae porta enim. Vestibulum urna leo, dapibus in ullamcorper quis, tempus in nibh. Curabitur semper augue eleifend ultricies ultrices.

Etiam iaculis sapien ante, eu feugiat dui venenatis id. Aliquam ac sodales enim. Proin vitae neque scelerisque, tempus urna sit amet, volutpat erat. Aenean dolor ante, auctor non purus eget, lacinia venenatis ligula. Vestibulum ullamcorper maximus nunc, sollicitudin mollis tortor vestibulum vitae. Duis feugiat quis ipsum in fringilla. Nam mollis arcu sed sagittis fringilla. Praesent gravida ipsum eu semper vehicula. Quisque sit amet auctor enim. Maecenas ut eros viverra dui placerat blandit nec eget massa. Integer mattis auctor ante, ut luctus libero faucibus quis. Aliquam pulvinar lacus et nisl dignissim volutpat. Etiam sit amet orci a turpis sollicitudin luctus.

Praesent finibus purus at massa ultricies vulputate. Etiam pellentesque, dui nec interdum interdum, leo dolor porta urna, ut eleifend erat eros non risus. Quisque venenatis venenatis ultrices. Quisque nec tortor id justo egestas fringilla sit amet et augue. Curabitur vulputate mauris mi, gravida pulvinar orci sodales in. Donec congue, odio vel elementum venenatis, sapien enim aliquet nibh, eget lacinia mi est ac tortor. Proin dolor augue, porttitor eget lobortis eget, aliquet vitae turpis.

Nulla hendrerit et diam eu facilisis. Aliquam justo ipsum, consectetur ac faucibus quis, dictum placerat tellus. Praesent ullamcorper bibendum orci, nec hendrerit dolor efficitur pellentesque. Duis at mollis est. Nullam laoreet bibendum hendrerit. Vivamus congue rhoncus mauris, eu sodales lorem congue non. Aliquam massa leo, euismod bibendum ornare vel, tincidunt eu metus. Maecenas in nisl et ipsum scelerisque aliquet. Integer consectetur sem non enim blandit fermentum.

Cras libero elit, posuere sed suscipit ut, tincidunt sed nisi. Nulla vel odio vestibulum, cursus sapien id, commodo nulla. Donec vulputate aliquam libero, vitae aliquet ipsum dignissim quis. Nullam consectetur egestas nibh, vitae pretium urna varius quis. Ut quis tincidunt erat. Nam tempus, sem at accumsan sagittis, massa massa hendrerit metus, vitae venenatis nunc ligula semper enim. Proin condimentum, mi nec ultricies porta, est odio scelerisque sem, et facilisis ipsum velit eu dolor. Donec porta enim at interdum laoreet. Cras bibendum libero arcu, sed lacinia ligula vehicula posuere. Aenean eget euismod magna, at maximus mauris. Vestibulum semper, eros eu placerat porttitor, magna odio tincidunt ligula, id tincidunt ipsum erat at diam. Nunc fermentum dui in tellus hendrerit, a ultrices ligula venenatis. Sed in risus a massa dictum feugiat. Aliquam erat volutpat. ', 'https://www.dropbox.com/s/oeqfye2gh9pmhdu/descarga.png?dl=1', '2018-03-06',1),

('El betis gana la Champions', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis orci at dolor mollis mollis. Suspendisse volutpat, sapien in sagittis aliquet, urna velit aliquam leo, non iaculis justo ante in tortor. Maecenas in tellus libero. Cras iaculis consectetur tellus eget pretium. Phasellus mollis orci a malesuada vestibulum. Suspendisse potenti. Morbi tincidunt tincidunt massa, ut maximus purus pellentesque eu. Nullam in consequat risus. Nullam aliquet vulputate nibh, id volutpat metus dapibus non. Donec vitae porta enim. Vestibulum urna leo, dapibus in ullamcorper quis, tempus in nibh. Curabitur semper augue eleifend ultricies ultrices.

Etiam iaculis sapien ante, eu feugiat dui venenatis id. Aliquam ac sodales enim. Proin vitae neque scelerisque, tempus urna sit amet, volutpat erat. Aenean dolor ante, auctor non purus eget, lacinia venenatis ligula. Vestibulum ullamcorper maximus nunc, sollicitudin mollis tortor vestibulum vitae. Duis feugiat quis ipsum in fringilla. Nam mollis arcu sed sagittis fringilla. Praesent gravida ipsum eu semper vehicula. Quisque sit amet auctor enim. Maecenas ut eros viverra dui placerat blandit nec eget massa. Integer mattis auctor ante, ut luctus libero faucibus quis. Aliquam pulvinar lacus et nisl dignissim volutpat. Etiam sit amet orci a turpis sollicitudin luctus.

Praesent finibus purus at massa ultricies vulputate. Etiam pellentesque, dui nec interdum interdum, leo dolor porta urna, ut eleifend erat eros non risus. Quisque venenatis venenatis ultrices. Quisque nec tortor id justo egestas fringilla sit amet et augue. Curabitur vulputate mauris mi, gravida pulvinar orci sodales in. Donec congue, odio vel elementum venenatis, sapien enim aliquet nibh, eget lacinia mi est ac tortor. Proin dolor augue, porttitor eget lobortis eget, aliquet vitae turpis.

Nulla hendrerit et diam eu facilisis. Aliquam justo ipsum, consectetur ac faucibus quis, dictum placerat tellus. Praesent ullamcorper bibendum orci, nec hendrerit dolor efficitur pellentesque. Duis at mollis est. Nullam laoreet bibendum hendrerit. Vivamus congue rhoncus mauris, eu sodales lorem congue non. Aliquam massa leo, euismod bibendum ornare vel, tincidunt eu metus. Maecenas in nisl et ipsum scelerisque aliquet. Integer consectetur sem non enim blandit fermentum.

Cras libero elit, posuere sed suscipit ut, tincidunt sed nisi. Nulla vel odio vestibulum, cursus sapien id, commodo nulla. Donec vulputate aliquam libero, vitae aliquet ipsum dignissim quis. Nullam consectetur egestas nibh, vitae pretium urna varius quis. Ut quis tincidunt erat. Nam tempus, sem at accumsan sagittis, massa massa hendrerit metus, vitae venenatis nunc ligula semper enim. Proin condimentum, mi nec ultricies porta, est odio scelerisque sem, et facilisis ipsum velit eu dolor. Donec porta enim at interdum laoreet. Cras bibendum libero arcu, sed lacinia ligula vehicula posuere. Aenean eget euismod magna, at maximus mauris. Vestibulum semper, eros eu placerat porttitor, magna odio tincidunt ligula, id tincidunt ipsum erat at diam. Nunc fermentum dui in tellus hendrerit, a ultrices ligula venenatis. Sed in risus a massa dictum feugiat. Aliquam erat volutpat. ', 'https://www.dropbox.com/s/oeqfye2gh9pmhdu/descarga.png?dl=1', '2018-03-06',1),

('El betis gana la Champions', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis orci at dolor mollis mollis. Suspendisse volutpat, sapien in sagittis aliquet, urna velit aliquam leo, non iaculis justo ante in tortor. Maecenas in tellus libero. Cras iaculis consectetur tellus eget pretium. Phasellus mollis orci a malesuada vestibulum. Suspendisse potenti. Morbi tincidunt tincidunt massa, ut maximus purus pellentesque eu. Nullam in consequat risus. Nullam aliquet vulputate nibh, id volutpat metus dapibus non. Donec vitae porta enim. Vestibulum urna leo, dapibus in ullamcorper quis, tempus in nibh. Curabitur semper augue eleifend ultricies ultrices.

Etiam iaculis sapien ante, eu feugiat dui venenatis id. Aliquam ac sodales enim. Proin vitae neque scelerisque, tempus urna sit amet, volutpat erat. Aenean dolor ante, auctor non purus eget, lacinia venenatis ligula. Vestibulum ullamcorper maximus nunc, sollicitudin mollis tortor vestibulum vitae. Duis feugiat quis ipsum in fringilla. Nam mollis arcu sed sagittis fringilla. Praesent gravida ipsum eu semper vehicula. Quisque sit amet auctor enim. Maecenas ut eros viverra dui placerat blandit nec eget massa. Integer mattis auctor ante, ut luctus libero faucibus quis. Aliquam pulvinar lacus et nisl dignissim volutpat. Etiam sit amet orci a turpis sollicitudin luctus.

Praesent finibus purus at massa ultricies vulputate. Etiam pellentesque, dui nec interdum interdum, leo dolor porta urna, ut eleifend erat eros non risus. Quisque venenatis venenatis ultrices. Quisque nec tortor id justo egestas fringilla sit amet et augue. Curabitur vulputate mauris mi, gravida pulvinar orci sodales in. Donec congue, odio vel elementum venenatis, sapien enim aliquet nibh, eget lacinia mi est ac tortor. Proin dolor augue, porttitor eget lobortis eget, aliquet vitae turpis.

Nulla hendrerit et diam eu facilisis. Aliquam justo ipsum, consectetur ac faucibus quis, dictum placerat tellus. Praesent ullamcorper bibendum orci, nec hendrerit dolor efficitur pellentesque. Duis at mollis est. Nullam laoreet bibendum hendrerit. Vivamus congue rhoncus mauris, eu sodales lorem congue non. Aliquam massa leo, euismod bibendum ornare vel, tincidunt eu metus. Maecenas in nisl et ipsum scelerisque aliquet. Integer consectetur sem non enim blandit fermentum.

Cras libero elit, posuere sed suscipit ut, tincidunt sed nisi. Nulla vel odio vestibulum, cursus sapien id, commodo nulla. Donec vulputate aliquam libero, vitae aliquet ipsum dignissim quis. Nullam consectetur egestas nibh, vitae pretium urna varius quis. Ut quis tincidunt erat. Nam tempus, sem at accumsan sagittis, massa massa hendrerit metus, vitae venenatis nunc ligula semper enim. Proin condimentum, mi nec ultricies porta, est odio scelerisque sem, et facilisis ipsum velit eu dolor. Donec porta enim at interdum laoreet. Cras bibendum libero arcu, sed lacinia ligula vehicula posuere. Aenean eget euismod magna, at maximus mauris. Vestibulum semper, eros eu placerat porttitor, magna odio tincidunt ligula, id tincidunt ipsum erat at diam. Nunc fermentum dui in tellus hendrerit, a ultrices ligula venenatis. Sed in risus a massa dictum feugiat. Aliquam erat volutpat. ', 'https://www.dropbox.com/s/oeqfye2gh9pmhdu/descarga.png?dl=1', '2018-03-06',1);
